# Generated by Django 4.2.2 on 2023-06-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('descriptionHTML', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('installs', models.CharField(max_length=255, null=True)),
                ('minInstalls', models.CharField(max_length=255, null=True)),
                ('realInstalls', models.CharField(max_length=255, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('ratings', models.BigIntegerField(null=True)),
                ('reviews', models.BigIntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('free', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=20)),
                ('sale', models.BooleanField(default=False)),
                ('originalPrice', models.IntegerField(null=True)),
                ('saleText', models.TextField(null=True)),
                ('offersIAP', models.BooleanField(default=False)),
                ('inAppProductPrice', models.CharField(max_length=255, null=True)),
                ('developer', models.CharField(max_length=255, null=True)),
                ('developerId', models.CharField(max_length=255, null=True)),
                ('developerEmail', models.EmailField(max_length=254, null=True)),
                ('developerWebsite', models.URLField(null=True)),
                ('developerAddress', models.TextField(null=True)),
                ('privacyPolicy', models.URLField(null=True)),
                ('genre', models.CharField(max_length=255, null=True)),
                ('genreId', models.CharField(max_length=255, null=True)),
                ('icon', models.URLField(null=True)),
                ('headerImage', models.URLField(null=True)),
                ('video', models.URLField(null=True)),
                ('videoImage', models.URLField(null=True)),
                ('contentRating', models.CharField(max_length=255, null=True)),
                ('contentRatingDescription', models.TextField(null=True)),
                ('adSupported', models.BooleanField(default=False)),
                ('containsAds', models.BooleanField(default=False)),
                ('released', models.DateField(null=True)),
                ('updated', models.BigIntegerField(null=True)),
                ('version', models.CharField(max_length=255, null=True)),
                ('appId', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(null=True)),
                ('categories', models.ManyToManyField(related_name='game_category', to='play_store_scraper.categories')),
            ],
        ),
        migrations.CreateModel(
            name='HistogramDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram', models.BigIntegerField()),
                ('game_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_histograms', to='play_store_scraper.gamedetails')),
            ],
        ),
        migrations.CreateModel(
            name='GamesPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_detail_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'GamesPaths',
                'db_table': 'GamesPaths',
                'indexes': [models.Index(fields=['app_detail_path'], name='GamesPaths_app_det_537f8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameScreenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.URLField()),
                ('game_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_screenshots', to='play_store_scraper.gamedetails')),
            ],
        ),
        migrations.AddField(
            model_name='gamedetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_details', to='play_store_scraper.gamespath'),
        ),
        migrations.CreateModel(
            name='GameComents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('game_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to='play_store_scraper.gamedetails')),
            ],
        ),
    ]
